services:
  - type: web
    name: laserbox-read-only-dashboard
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: MQTT_USERNAME
        sync: false
      - key: MQTT_PASSWORD
        sync: false
